---
revision: '2025-03-11'
supported:
  RHEL-8:
    - package: scap-security-guide-rule-playbooks-0.1.76-1.el8.noarch.rpm
      version: 0.1.76
      brew_url: https://download.devel.redhat.com/brewroot/vol/rhel-8/packages/scap-security-guide/0.1.76/1.el8/noarch/scap-security-guide-rule-playbooks-0.1.76-1.el8.noarch.rpm
  RHEL-9:
    - package: scap-security-guide-rule-playbooks-0.1.76-1.el9.noarch.rpm
      version: 0.1.76
      brew_url: https://download.devel.redhat.com/brewroot/vol/rhel-9/packages/scap-security-guide/0.1.76/1.el9/noarch/scap-security-guide-rule-playbooks-0.1.76-1.el9.noarch.rpm
